import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "./_components/Header";
import clsx from "clsx";
import { ClerkProvider } from "@clerk/nextjs";
import Footer from "./_components/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
    <html lang="en" className="relative">
      <body className={clsx(inter.className, "antialiased bg-[#F9D1D1]")}>
        <Header />
        {children}
        <Footer />
        </body>
    </html>
    </ClerkProvider>
  );
}
